language: swift
xcode_project: HM10 Serial.xcodeproj # path to your xcodeproj folder
xcode_scheme: Serial
osx_image:
    - xcode7.3
    - xcode8
    - xcode8.1
    - xcode8.2
    - xcode8.3
xcode_sdk:
    - iphonesimulator8.4
    - iphonesimulator9.3
    - iphonesimulator10.0
    - iphonesimulator10.1
    - iphonesimulator10.2
    - iphonesimulator10.3